### ISSUE TITLE
Erro ao usar a função `plot()` do pacote PSF 

### ISSUE THREAD

**Issue by jracker** [jracker/testePSF#1]
O erro ocorre ao usar a função `plot()` com os argumentos conforme mostrado no código a seguir

```
qnat_posto74<- qnat_posto74[10:length(qnat_posto74$qnat),]

modelo_munhoz = psf(qnat_posto74, cycle = 12) 

(pred_munhoz = predict(modelo_munhoz, n.ahead = 12))

(obs <- qnat_posto74$qnat[580:591]) # Valores de vazão dos últimos 12 meses

plot(modelo_munhoz, pred_munhoz)
```

Após executar a função `plot()` ocorre o seguinte erro:

`
Error in xy.coords(x, NULL, log = log, setLab = FALSE) : 
  'list' object cannot be coerced to type 'double'
`

Será que é necessário transformar os dados do tipo `dataframe` para séries temporais, como é feito nos exemplos do pacote PSF?

**Comment by lhmet** [comment]
@jracker eu usei a versão do github do PSF, dá olhada no meu fork do teu repo. Consegui rodar o PSF. Tentei fazer pull request, mas não obtive sucesso. Acho que é porque fiz muitas alterações, incluindo no nome dos diretórios.

**Comment by jracker** [comment]
Com as suas alterações consegui rodar sem problemas na versão do CRAN (0.4).
